const TEAM = [
  "Dr. Meraj Aman","Dr. Nabila","Dr. Zohaib Manzoor","Dr. Noreen","Dr. Uswa Maryam","Dr. Sehreen"
];
const teams=["Team Enamel","Team Dentin","Team Molar","Team Incisor"];
const missions=[
 {title:"Plaque Detective",icon:"🔎",desc:"Spot the things that can put a smile at risk.",points:250},
 {title:"Sugar Trap",icon:"🍭",desc:"Make smart choices about foods, drinks and frequency.",points:250},
 {title:"Brushing Battle",icon:"🪥",desc:"Clean the plaque from the whole mouth.",points:250},
 {title:"Myth or Fact",icon:"🧠",desc:"Separate dental facts from common myths.",points:250},
 {title:"Save the Tooth",icon:"🚨",desc:"Build a smart rescue plan for Ahmed.",points:250}
];
const state={team:"",score:0,completed:0,badges:[],sound:true,animations:true,selectedTeam:""};
const $=id=>document.getElementById(id);
function save(){localStorage.setItem("dqState",JSON.stringify(state))}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem("dqState")||"{}"))}catch{}}
function screen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active"));$(id).classList.add("active");$("hud").hidden=["home","how","setup"].includes(id);window.scrollTo({top:0,behavior:"smooth"});updateHud()}
function updateHud(){$("hudTeam").textContent=state.team||"Team";$("hudScore").textContent=state.score;$("mapScore").textContent=state.score}
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1800)}
function award(n){state.score+=n;updateHud();save();toast(`+${n} points!`)}
function renderTeam(){ const files=["male-doctor.png","female-doctor.png","male-doctor.png","female-doctor.png","female-doctor.png","female-doctor.png"]; $("teamGrid").innerHTML=TEAM.map((n,i)=>`<article class="team-card"><div class="avatar"><img src="assets/avatars/${files[i]}" alt="${i===0||i===2?"Male":"Female"} dental doctor illustration"></div><div><h3>${n}</h3><p>BDS Community Dentistry Team</p></div></article>`).join("") }
function renderChoices(){ $("teamChoices").innerHTML=teams.map(t=>`<button class="choice" data-team="${t}">🦷 ${t}</button>`).join("");document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");state.selectedTeam=b.dataset.team;$("customTeam").value=""})}
function renderMap(){ $("missionMap").innerHTML=missions.map((m,i)=>{const unlocked=i<=state.completed,done=i<state.completed;return `<button class="mission-node ${unlocked?"":"locked"}" data-m="${i}" ${unlocked?"":"disabled"}><span class="mission-num">MISSION ${String(i+1).padStart(2,"0")}</span><span class="mission-icon">${m.icon}</span><div><h3>${m.title}</h3><small>${m.desc}</small><div class="status ${done?"done":""}">${done?"✓ COMPLETED":unlocked?"▶ START MISSION":"🔒 LOCKED"}</div></div></button>`}).join("");document.querySelectorAll(".mission-node:not(.locked)").forEach(b=>b.onclick=()=>openMission(+b.dataset.m))}
function openMission(i){$("missionCounter").textContent=`${String(i+1).padStart(2,"0")} / 05`;$("progressFill").style.width=`${(i/5)*100}%`;screen("mission");renderMission(i)}
function complete(i,badge){if(i>=state.completed)state.completed=i+1;if(badge&&!state.badges.includes(badge))state.badges.push(badge);save();updateHud();renderMap()}
function next(i){if(i<4)screen("map"),renderMap();else finish()}
function renderMission(i){
 const m=missions[i];let c=`<div class="challenge"><span class="eyebrow">MISSION ${String(i+1).padStart(2,"0")} • ${m.title.toUpperCase()}</span><h2>${m.icon} ${m.title}</h2>`;
 if(i===0)c+=`<p class="challenge-intro">You found a suspicious mouth. Tap the items that can contribute to dental problems. There may be more than one.</p><div class="click-grid" id="plaqueGrid">
 ${["🦠 Plaque","🍬 Sugar","🍎 Apple","🥤 Sugary drink","🪥 Toothbrush","🍽️ Food debris"].map((x,j)=>`<button class="item-card" data-risk="${[0,1,3,5].includes(j)}">${x}</button>`).join("")}</div><button class="btn primary" id="checkMission" style="margin-top:20px">Check my evidence</button><div id="feedback"></div>`;
 if(i===1)c+=`<p class="challenge-intro">Sort the choices. Think about what you would choose regularly and what should be limited in frequency because of free sugars.</p><div class="click-grid" id="sugarGrid">
 ${["🥤 Soft drink","🍭 Candy","🍫 Chocolate","🍪 Biscuits","🍎 Apple","🥕 Carrot","💧 Water","🥛 Milk"].map((x,j)=>`<button class="item-card" data-limit="${j<4}">${x}</button>`).join("")}</div><button class="btn primary" id="checkMission" style="margin-top:20px">Check choices</button><div id="feedback"></div>`;
 if(i===2)c+=`<p class="challenge-intro">Use the controls to brush each tooth area. Your goal is to remove the visible plaque.</p><div class="mouth" id="mouth">${Array.from({length:15},(_,j)=>`<button class="tooth plaque" data-tooth="${j}" aria-label="Tooth ${j+1}"></button>`).join("")}</div><div class="progress-large"><span id="brushProgress"></span></div><p id="brushText" class="muted">0 / 15 tooth areas cleaned</p><div class="brush-zone"><button class="brush-control" id="brushBtn">🪥 Brush next area</button><button class="btn primary" id="finishBrush" disabled>Complete mission</button></div><div id="feedback"></div>`;
 if(i===3){c+=`<p class="challenge-intro">10-question Class 6 challenge. Read carefully and choose <b>MYTH</b> or <b>FACT</b>.</p><div id="mythQuestion"></div><div class="quiz-progress"><span id="mythProgress">Question 1 of 10</span></div>`} if(i===4)c+=`<p class="challenge-intro">Ahmed is 12. He often drinks sugary drinks, snacks frequently, brushes inconsistently, has plaque and toothache, and has not had dental care recently. Build the safest rescue plan.</p><div class="case-card"><b>Choose the actions that belong in a smart plan.</b></div><div class="actions-grid" id="actions">
 ${["🪥 Improve toothbrushing","💧 Choose water regularly","🍭 Reduce frequent sugary exposures","👩‍⚕️ Seek professional dental care","🦷 Use fluoride toothpaste","❌ Ignore the toothache","❌ Brush extremely hard","❌ Share a toothbrush"].map((x,j)=>`<button class="action" data-good="${j<5}">${x}</button>`).join("")}</div><button class="btn primary" id="checkMission" style="margin-top:20px">Submit rescue plan</button><div id="feedback"></div>`;
 $("missionContent").innerHTML=c;
 if(i===0||i===1){document.querySelectorAll(".item-card").forEach(b=>b.onclick=()=>b.classList.toggle("selected"));$("checkMission").onclick=()=>checkClassify(i)}
 if(i===2)setupBrush();
 if(i===3)setupMyth();
 if(i===4){document.querySelectorAll(".action").forEach(b=>b.onclick=()=>b.classList.toggle("selected"));$("checkMission").onclick=()=>checkActions()}
}
function checkClassify(i){const buttons=[...document.querySelectorAll(".item-card")];const good=i===0?buttons.filter(b=>b.dataset.risk==="true"):buttons.filter(b=>b.dataset.limit==="true");const selected=buttons.filter(b=>b.classList.contains("selected"));let ok=selected.length===good.length&&selected.every(b=>good.includes(b));buttons.forEach(b=>{if((i===0?b.dataset.risk:b.dataset.limit)==="true")b.classList.add("correct")});$("feedback").innerHTML=`<div class="feedback ${ok?"good":"bad"}>${ok?"✓ Excellent detective work!":"Good try — review the highlighted choices."}</div><div class="explain">${i===0?"Plaque is a sticky film containing bacteria. Food and frequent free-sugar exposure can contribute to caries risk; brushing helps remove plaque.":"Frequent exposure to free sugars increases the risk of dental caries. You do not need to label every food as forbidden — frequency and overall habits matter."}</div><button class="btn primary" style="margin-top:18px" id="continue">Continue →</button>`;$("continue").onclick=()=>{award(ok?100:50);complete(i,i===0?"Plaque Detective":"Smart Choice Champion");next(i)}}
function setupBrush(){let cleaned=0;document.querySelectorAll(".tooth").forEach(t=>t.onclick=()=>{if(!t.classList.contains("cleaned")){t.classList.add("cleaned");cleaned++;updateBrush(cleaned)}});$("brushBtn").onclick=()=>{const t=[...document.querySelectorAll(".tooth")].find(x=>!x.classList.contains("cleaned"));if(t){t.classList.add("cleaned");cleaned++;updateBrush(cleaned)}};function updateBrush(n){$("brushProgress").style.width=`${n/15*100}%`;$("brushText").textContent=`${n} / 15 tooth areas cleaned`;if(n===15){$("finishBrush").disabled=false;$("feedback").innerHTML=`<div class="feedback good">🎉 Mouth cleaned! Great work.</div><div class="explain">Brush effectively with fluoride toothpaste. Aim to clean all tooth surfaces rather than brushing harder.</div>`}}$("finishBrush").onclick=()=>{award(250);complete(2,"Brushing Boss");next(2)}}
function setupMyth(){const qs=[
["Brushing harder always cleans teeth better.","Myth","Gentle, thorough brushing is better than brushing too hard."],["Plaque contains bacteria.","Fact","Plaque is a sticky film containing bacteria."],["You only need a dentist when your tooth hurts.","Myth","Dental visits can also help prevent problems and find them early."],["Water is a tooth-friendly drink.","Fact","Water is a good regular drink choice."],["Fluoride toothpaste helps prevent dental caries.","Fact","Fluoride toothpaste helps protect teeth from decay."],["Milk teeth are completely unimportant.","Myth","Primary teeth help with eating, speech and keeping space for permanent teeth."],["Sharing toothbrushes is a good idea.","Myth","Toothbrushes should not be shared."],["Frequent sugary snacks can increase caries risk.","Fact","Frequent exposure to free sugars increases caries risk."],["Plaque can be removed through effective toothbrushing.","Fact","Effective toothbrushing helps remove plaque."],["Oral health is connected with overall wellbeing.","Fact","A healthy mouth is an important part of overall health."];
let qi=0,pts=0;function show(){const q=qs[qi];$("mythQuestion").innerHTML=`<div class="case-card"><small>QUESTION ${qi+1} / 10</small><h3>“${q[0]}”</h3></div><div class="mcq"><button class="answer" data-answer="Fact">✅ FACT</button><button class="answer" data-answer="Myth">❌ MYTH</button></div><div id="feedback"></div>`;$("mythProgress").textContent=`Question ${qi+1} of 10`;document.querySelectorAll(".answer").forEach(b=>b.onclick=()=>{document.querySelectorAll(".answer").forEach(x=>x.disabled=true);const ok=b.dataset.answer===q[1];b.classList.add(ok?"correct":"wrong");pts+=ok?100:25;$("feedback").innerHTML=`<div class="feedback ${ok?"good":"bad"}">${ok?"✓ Correct!":"Not quite."}</div><div class="explain">${q[2]}</div>`;setTimeout(()=>{qi++;if(qi<10)show();else{state.score+=pts;complete(3,"Dental Genius");$("feedback").innerHTML+=`<div class="feedback good" style="margin-top:12px">🧠 Mission complete! +${pts} points</div><button class="btn primary" id="continueQuiz" style="margin-top:16px">Continue →</button>`;$("continueQuiz").onclick=()=>{save();next(3)}}},700)})}show()}
function checkActions(){const b=[...document.querySelectorAll(".action")],good=b.filter(x=>x.dataset.good==="true"),sel=b.filter(x=>x.classList.contains("selected"));const ok=sel.length===good.length&&sel.every(x=>good.includes(x));b.forEach(x=>{if(x.dataset.good==="true")x.classList.add("correct")});$("feedback").innerHTML=`<div class="feedback ${ok?"good":"bad"}>${ok?"🚨 Tooth rescued!":"Review the plan — some actions are unsafe or not helpful."}</div><div class="explain">A smart plan includes effective brushing with fluoride toothpaste, reducing frequent sugary exposures, choosing water regularly and seeking professional dental care for problems such as toothache.</div><button class="btn primary" style="margin-top:18px" id="finishCase">Finish Quest →</button>`;$("finishCase").onclick=()=>{award(ok?300:150);complete(4,"Tooth Hero");finish()}}
function finish(){state.completed=5;save();$("finalScore").textContent=state.score;$("resultTeam").textContent=state.team;$("resultMissions").textContent="5 / 5";$("resultBadges").textContent=state.badges.length;saveResult();screen("results")}
function saveResult(){let rows=JSON.parse(localStorage.getItem("dqLeaderboard")||"[]");rows.push({team:state.team,score:state.score,badge:"Dental Quest Champion"});rows=rows.sort((a,b)=>b.score-a.score).slice(0,20);localStorage.setItem("dqLeaderboard",JSON.stringify(rows))}
function renderLeaderboard(){let rows=JSON.parse(localStorage.getItem("dqLeaderboard")||"[]");$("leaderRows").innerHTML=rows.length?rows.map((r,i)=>`<div class="leader-row"><span class="rank">${["🥇","🥈","🥉"][i]||i+1}</span><b>${escapeHtml(r.team)}</b><span>${r.score} pts</span><span>🏆 ${r.badge}</span></div>`).join(""):`<div class="leader-row"><span>—</span><b>No scores yet</b><span>0</span><span>Start a quest!</span></div>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function resetGame(){Object.assign(state,{team:"",score:0,completed:0,badges:[],selectedTeam:""});save();renderMap();screen("home");toast("Game reset")}
load();renderTeam();renderChoices();renderMap();updateHud();
$("startBtn").onclick=()=>screen("setup");$("howBtn").onclick=()=>screen("how");$("howStart").onclick=()=>screen("setup");
$("beginBtn").onclick=()=>{const custom=$("customTeam").value.trim();state.team=custom||state.selectedTeam;if(!state.team){toast("Choose a team first");return}state.score=0;state.completed=0;state.badges=[];save();renderMap();screen("map")};
$("backMap").onclick=()=>{renderMap();screen("map")};
$("leaderBtn").onclick=()=>{renderLeaderboard();screen("leaderboard")};$("leaderHome").onclick=()=>screen("home");$("restartBtn").onclick=()=>resetGame();
$("resetLeaderboard").onclick=()=>{if(confirm("Reset the classroom leaderboard?")){localStorage.removeItem("dqLeaderboard");renderLeaderboard();toast("Leaderboard reset")}};
$("menuBtn").onclick=()=>{const pin=prompt("Facilitator PIN");if(pin==="1234"){renderFac();screen("facilitator")}else if(pin!==null)toast("Incorrect PIN")};
$("facMap").onclick=()=>{renderMap();screen("map")};$("facReset").onclick=()=>resetGame();$("facLeaderReset").onclick=()=>{localStorage.removeItem("dqLeaderboard");toast("Leaderboard reset")};
$("soundBtn").onclick=()=>{state.sound=!state.sound;$("soundBtn").textContent=state.sound?"🔊":"🔇";save()};
$("modalClose").onclick=()=>$("modal").hidden=true;
function renderFac(){$("facTeam").textContent=state.team||"—";$("facScore").textContent=state.score;$("facMission").textContent=`${state.completed} / 5`}
